:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore ../\OpenapiGenerator.Server
dotnet build ../\OpenapiGenerator.Server
echo Now, run the following to start the project: dotnet run -p ../\OpenapiGenerator.Server\OpenapiGenerator.Server.csproj --launch-profile web.
echo.
